ARG IMAGE=node:14.17-alpine
ARG NODE_ENV=production

FROM $IMAGE as build
ENV CYPRESS_INSTALL_BINARY=false

WORKDIR /usr/usr/app

COPY . .

ENV NODE_ENV $NODE_ENV

RUN npm install --quiet --no-progress -g nx && \
    npm ci --quiet --no-progress
RUN nx build dsb-client-gateway-frontend


FROM $IMAGE

WORKDIR /usr/app

USER node

COPY --chown=node:node --from=build /usr/app/dist/apps/dsb-client-gateway-frontend/* /usr/app/
RUN npm install --production

CMD ["npm", "start"]
