version: '3'
services:
  vault_dev:
    image: hashicorp/vault:latest
    restart: always
    volumes:
      - /vault/data
      - /etc/vault/logs
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    container_name: vault_dev
    entrypoint: "vault server -dev"

  ddhub-gateway-UI:
    image: aemocontainerregistry.azurecr.io/ddhub-client-gateway-frontend:canary
    ports:
      - "3000:80"

  ddhub-gateway-api:
    image: aemocontainerregistry.azurecr.io/ddhub-client-gateway-backend:canary
    container_name: ddhub-gateway-api
    depends_on:
      - 'vault_dev'
    ports:
      - 3333:3333
    environment:
      NODE_ENV: test
      DSB_BASE_URL: https://ddhub-demo.energyweb.org
      CACHE_SERVER_URL: https://identitycache-staging.energyweb.org/v1
      EVENT_SERVER_URL: https://identityevents-staging.energyweb.org
      SECRETS_ENGINE: vault
      VAULT_ENDPOINT: http://vault_dev:8200
      VAULT_TOKEN: root

  proxy-server:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3009:80"
    depends_on:
      - ddhub-gateway-UI
      - ddhub-gateway-api
